# -*- coding: utf-8 -*-
"""
Calibrate the minimum llm_confidence required before node_fusion.py treats
an LLM 'MATCH' verdict as an actual merge, using the same golden-set
methodology calibrate_threshold.py already uses for the FAISS similarity
floor -- sweep candidate thresholds against annotated ground truth and find
where precision/recall actually land, rather than asserting a number.

This is NOT the same question calibrate_threshold.py answers. That script
finds where FAISS similarity alone can bypass the LLM. This one only looks
at pairs the LLM already called MATCH, and asks: among those, at what
confidence floor does precision (how many of the surviving MATCHes are
real, per human annotation) become acceptable, and how many genuine matches
would get thrown out by requiring it (recall against the LLM's own true
positives). A MATCH the LLM was unconfident about is exactly the case this
floor is meant to catch -- a confident MATCH should sail through untouched.

Requires an llm_resolved.csv that was generated by the CURRENT
llm_judgement.py (the one that emits 'MATCH <confidence>' /
'NO_MATCH <confidence>') run against the golden set itself -- an
llm_resolved.csv from before that change has no llm_confidence column and
can't be used here.

Usage:
    python calibrate_llm_confidence.py \
        --golden_set   openai_golden_entity_pairs.csv \
        --llm_resolved openai_llm_resolved.csv \
        --plot_output  llm_confidence_calibration_plot.png \
        --log_output   llm_confidence_calibration_log.txt
"""

import argparse
import datetime
import logging

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import precision_score, recall_score

MERGE_COLS = ['entity_label_1', 'evidence_1', 'entity_label_2', 'evidence_2']


def calibrate(golden_set_path, llm_resolved_path, log_fh):
    df_golden = pd.read_csv(golden_set_path)
    df_golden['label'] = df_golden['label'].astype(str).str.strip().str.upper()
    df_golden = df_golden[df_golden['label'].isin(['MATCH', 'NO_MATCH'])].copy()

    df_llm = pd.read_csv(llm_resolved_path)
    if 'llm_confidence' not in df_llm.columns:
        raise SystemExit(
            f"{llm_resolved_path} has no 'llm_confidence' column -- it was generated "
            "before the confidence-emitting prompt change. Re-run llm_judgement.py "
            "against the golden set with the current code first."
        )

    for col in MERGE_COLS:
        df_golden[col] = df_golden[col].astype(str).str.strip()
        df_llm[col] = df_llm[col].astype(str).str.strip()

    df_eval = pd.merge(
        df_golden, df_llm[MERGE_COLS + ['llm_prediction', 'llm_confidence']],
        on=MERGE_COLS, how='inner'
    )
    if len(df_eval) == 0:
        raise SystemExit("Could not match any rows between golden set and LLM output. Check column names.")

    # Only rows the LLM actually called MATCH matter here -- a NO_MATCH never
    # merges regardless of confidence, so it's not part of this calibration.
    df_llm_matches = df_eval[df_eval['llm_prediction'] == 'MATCH'].copy()
    total_llm_matches = len(df_llm_matches)
    total_true_matches_among_them = int((df_llm_matches['label'] == 'MATCH').sum())

    log_fh.write(f"{'='*50}\nLLM CONFIDENCE CALIBRATION\n{'='*50}\n")
    log_fh.write(f"Total golden pairs evaluated: {len(df_eval)}\n")
    log_fh.write(f"LLM predicted MATCH on: {total_llm_matches} of them "
                 f"({total_true_matches_among_them} genuinely true per annotation, "
                 f"{total_llm_matches - total_true_matches_among_them} false positives)\n\n")

    if total_llm_matches == 0:
        log_fh.write("No LLM MATCH predictions to calibrate against.\n")
        return None, None, None, None

    y_true = (df_llm_matches['label'] == 'MATCH').astype(int).values
    scores = df_llm_matches['llm_confidence'].astype(float).values

    thresholds = np.linspace(0.0, 1.0, 200)
    precisions, recalls = [], []
    for t in thresholds:
        keep = (scores >= t).astype(int)
        # Precision here = of the pairs that SURVIVE the floor, how many are
        # genuinely true matches. Recall = of the LLM's own true positives,
        # how many survive the floor (i.e. how many correct merges are NOT
        # thrown out by requiring this confidence).
        precisions.append(precision_score(y_true, keep, zero_division=1))
        recalls.append(recall_score(y_true, keep, zero_division=0))

    # Lowest floor that achieves >=98% precision among survivors, same bar
    # calibrate_threshold.py uses for its auto-match threshold.
    valid = [thresholds[i] for i in range(len(thresholds))
             if precisions[i] >= 0.98 and recalls[i] > 0]
    min_confidence = min(valid) if valid else None

    if min_confidence is not None:
        kept = int((scores >= min_confidence).sum())
        log_fh.write(f"MINIMUM LLM_CONFIDENCE FLOOR: {min_confidence:.4f} "
                     f"(>=98% precision among surviving MATCHes)\n")
        log_fh.write(f"  Would keep {kept} / {total_llm_matches} LLM MATCH predictions as real merges, "
                     f"discarding {total_llm_matches - kept} as too-uncertain.\n\n")
    else:
        log_fh.write("No confidence floor achieves 98% precision among LLM MATCH predictions -- "
                      "the LLM's false positives aren't separable by its own stated confidence "
                      "in this sample. Consider a lower precision bar or more golden pairs.\n\n")

    return thresholds, precisions, recalls, min_confidence


def main():
    parser = argparse.ArgumentParser(
        description="Calibrate the minimum llm_confidence floor for node_fusion.py, from golden pairs."
    )
    parser.add_argument("--golden_set",   required=True, help="Annotated golden set CSV")
    parser.add_argument("--llm_resolved", required=True,
                        help="llm_judgement.py output run against the golden set (must have llm_confidence)")
    parser.add_argument("--plot_output",  default="llm_confidence_calibration_plot.png")
    parser.add_argument("--log_output",   default="llm_confidence_calibration_log.txt")
    args = parser.parse_args()

    with open(args.log_output, "w") as log_fh:
        log_fh.write(f"Calibration run: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        thresholds, precisions, recalls, min_confidence = calibrate(
            args.golden_set, args.llm_resolved, log_fh
        )
    print(f"Log saved to {args.log_output}")

    if thresholds is None:
        return

    fig, ax = plt.subplots(figsize=(8, 6), dpi=300)
    ax.plot(thresholds, precisions, label='Precision (among survivors)', color='#1f77b4', linewidth=2.5)
    ax.plot(thresholds, recalls, label="Recall (of LLM's own true positives)", color='#ff7f0e', linewidth=2.5)
    if min_confidence is not None:
        ax.axvline(x=min_confidence, color='green', linestyle='--', linewidth=1.5,
                   label=f'Min confidence floor ($\\tau={min_confidence:.4f}$)')
        ax.axvspan(min_confidence, 1, color='green', alpha=0.1)
        ax.axvspan(0, min_confidence, color='red', alpha=0.1)
    ax.set_title("LLM Confidence Calibration (among MATCH predictions)", fontsize=14, pad=10)
    ax.set_xlabel('llm_confidence', fontsize=12)
    ax.set_ylabel('Metric Score', fontsize=12)
    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 1.05])
    ax.grid(True, linestyle=':', alpha=0.7)
    ax.legend(loc='lower left', fontsize=10, framealpha=0.9, edgecolor='black')
    plt.tight_layout()
    plt.savefig(args.plot_output, format='png', bbox_inches='tight')
    plt.savefig(args.plot_output.replace('.png', '.pdf'), format='pdf', bbox_inches='tight')
    print(f"Plot saved to {args.plot_output} (and .pdf)")


if __name__ == "__main__":
    main()
